# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: cypress/base:10
        environment:
          ## this enables colors in the output
          TERM: xterm

    # working_directory: ~/public

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm ci

      - save_cache:
          paths:
            - ~/.npm
            - ~/.cache
          key: v1-dependencies-{{ checksum "package.json" }}

      # Build site!
      - run:
          name: Build the portfolio with the Gatsby
          command: npm run build

      - run:
          name: Serve the portfolio site
          command: npm run serve

      - run:
          name: Run end to end tests with Cypress
          command: npm run e2e
